name: CYBER GHOST IP Updater

on:
  schedule:
    - cron: '30 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-iocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and zmap
        run: |
          python -m pip install --upgrade pip
          pip install dnspython
          pip install requests
          sudo apt install zmap

      - name: Gather PIA subnets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python pia.py

      - name: Generate custom blocklist 
        run: python cyberghost_blocklist_generator.py

      - name: CyberGhost Scan
        run: sudo zmap  -M udp -p 443 --probe-args=file:openvpn_1194.pkt -w pia_subnet.txt -b custom_blocklist.txt -r 128 -O csv --output-filter="success = 1" -o 'cyberghost_ips_temp.csv'
        
      - name: Clean up zmap output(C)
        run: python cyberghost_ip_cleanup.py


      - name: Configure Git
        run: |
          git config --local user.email "sudesh@sudesh.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          git add cyberghost_ips.csv new_cyberghost_ips.csv
          git diff-index --quiet HEAD || git commit -m "[AUTO] update IoCs $(date '+%Y-%m-%d %H:%M:%S')"
          
      - name: Push changes
        id: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

